### ISSUE TITLE
enabled keepUndefinedParameters by default in our jenkins master

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#106]
to support on pull request job we have to allow below property as part of jenkins setup:
System.setProperty("hudson.model.ParametersAction.keepUndefinedParameters", "true")

**Comment by vdelendik** [comment]
don't forget to update manual deployment readme for this or put this command into appropriate groovy script

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/107

**Comment by vdelendik** [comment]
done
