### ISSUE TITLE
remove gc_GIT_BRANCH global choice list

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#112]
no need to gerisget global choice list for browsers anymore of jenkins layer. It should be fixed only after: https://github.com/qaprosoft/qps-pipeline/issues/556

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/118

**Comment by ilya-varchenya** [comment]
Related issue to https://github.com/qaprosoft/jenkins-master/issues/112

**Comment by okamara** [comment]
Verified on develop branch
