### ISSUE TITLE
publish README.txt steps into the root with high level steps howto start with infra

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#114]
![image](https://user-images.githubusercontent.com/4551455/71383820-210af880-25ef-11ea-9e54-6f714c1f0e78.png)

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/72349105-ee838580-36ec-11ea-8383-8ec27c70927a.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/129

**Comment by ilya-varchenya** [comment]
@okamara, please check that README.txt (it is a job) appeared in updated jenkins-master
This job must contains next description
![image](https://user-images.githubusercontent.com/44428408/72349402-841f1500-36ed-11ea-940b-e8e1be1410ee.png)

**Comment by okamara** [comment]
Verified. Done.
