### ISSUE TITLE
remove braces around ${QPS_PIPELINE_GIT_URL} and ${QPS_PIPELINE_GIT_BRANCH}

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#115]
default values should be:
$QPS_PIPELINE_GIT_URL
$QPS_PIPELINE_GIT_BRANCH

it should fix error in jenkins logs:
Jan 03, 2020 3:46:48 PM WARNING com.cloudbees.jenkins.GitHubRepositoryName create
Could not match URL ${QPS_PIPELINE_GIT_URL}

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/116

**Comment by ilya-varchenya** [comment]
@okamara, 
To check this issue:
1. you should run **clear.sh**
2. rebuild **jenkis-master image** localy
3. run **./star.sh**
4. check that Manage Jenkins/Configure Jenkins doesn't have braces in that parameters
![image](https://user-images.githubusercontent.com/44428408/71765715-20386780-2f09-11ea-9ce5-c0bc746a7385.png)

**Comment by okamara** [comment]
Verified on develop branch
