### ISSUE TITLE
add information about required java opts to manual deployment guide

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#123]
Starting from 4.8+ jenkins-master we have to add below java option to make onPullrequest-<repo>-trigger workable: https://github.com/qaprosoft/qps-infra/commit/4bddc573d5296150d2de39cff4ebb2a60be9895f

Add an additional system argument in docker-compose.yml with "JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true" in your docker-compose.yml file for jenkins-master to make a new onPullRequest checker job workable
Note: for additional details, follow the link

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/127

**Comment by ilya-varchenya** [comment]
New info in manual deployment readme
![image](https://user-images.githubusercontent.com/44428408/72344415-3bae2a00-36e2-11ea-9f4e-3d024af69e20.png)

**Comment by okamara** [comment]
Verified.
