### ISSUE TITLE
setup by default github pull request builder

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#130]
To do it manually such steps needed:
Manage Jenkins -> Configure System
Specify a value for GitHub Server API URL, for example, https://api.github.com
Provide GitHub credentials with Admin privileges for your organization
Check the "Auto-manage webhooks" param
Update "Commit Status Context" to a value such as "qps-infra"

Initially let's create credentials with:
id: ghprbhook-token
username: CHANGE_ME
password: CHANGE_ME
Decription: Github Pull Request Builder token

**Comment by ilya-varchenya** [comment]
![image](https://user-images.githubusercontent.com/44428408/73334319-73d67080-427d-11ea-965e-d5646e81063e.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/136

**Comment by okamara** [comment]
Tested. Fixed.
