### ISSUE TITLE
full console logs can't be opened due to the timestamper plugin issue

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#131]
https://issues.jenkins-ci.org/browse/JENKINS-60672
JENKINS-60672 Timestamper plugin causes chrome frozen when there are too many console logs

try to decreate timestamper plugin version or remove it completely from default list to avoid huge performance degradation even on pretty small full console logs (~1Mb)

**Comment by okamara** [comment]
Verified. Tested in 4.9-beta5 jenkins-master.
