### ISSUE TITLE
RegisterUserCredentials - add extra description

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#137]
Let's add description for RegisterUserCredentials job:
To be able to run vs forked repository each engineer should register his personal token by this job

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/140

**Comment by ilya-varchenya** [comment]
@okamara , please check that Managment Jobs have new description:
**RegisterOrganization**: Register SCM organization folder on CI (github, gitlab etc)
**DeleteOrganization**: Delete SCM organization folder on CI
**RegisterUserCredentials**: Register personal SCM tokens and their assosiation with jenkins user to support execution vs forked repositories
**RegisterZafiraCredentials**: Register unique Zafira instance per SCM organization

**Comment by okamara** [comment]
Tested. Fixed.
