### ISSUE TITLE
zafiraServiceURL and zafiraAccessToken should have default values

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/jenkins-master#150]
Update RegisterOrganization job with default values for zafiraServiceURL and zafiraAccessToken parameters

Also we need to add description how to setup zafiraServiceURL and zafiraAccessToken parameters if organisation uses not default values

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/151

**Comment by ilya-varchenya** [comment]
@okamara and @dhreben, please, verify that RegisterOrganisation job has a new description and default values for zafiraServiceURL and zafiraAccessToken parameters are set
![image](https://user-images.githubusercontent.com/44428408/77322030-2679fb00-6d24-11ea-92be-75d23315d237.png)
![image](https://user-images.githubusercontent.com/44428408/77322416-bd46b780-6d24-11ea-97d5-c495822e4543.png)

**Comment by ilya-varchenya** [comment]
Use qaprosoft/jenkins-master:4.10-beta3 tag in docked-compose.yml

**Comment by okamara** [comment]
Tested, fixed
