### ISSUE TITLE
add gradle 'G6' global tool into the jenkins-master

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#152]
![image](https://user-images.githubusercontent.com/4551455/77488347-f4f95080-6e45-11ea-86d1-83a1f4c1425c.png)

using this toll we can start developing gradle runner(s)

**Comment by ilya-varchenya** [comment]
Need more information

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/170/files

![image](https://user-images.githubusercontent.com/44428408/78761127-dab58b80-798a-11ea-8621-037b59985745.png)

**Comment by ilya-varchenya** [comment]
@dhreben or @okamara, please, verify with the next steps:
1. Update jenkins-master
1.1 open terminal
1.2 go to qps-infra folder
1.3 `nano docker-compose.yml`
1.4 change jenkins-master container's name (ask me for it)
1.5 save end exit
2. delete jenkins folder content: `rm -rf ./jenkins/*`
3. `./start.sh`
4. wait for a couple of minutes
5. open Jenkins -> Manage Jenkins -> Global tool configuration
6. press on a button near Gradle
7. verify that all fields has values as it's showed of a picture

**Comment by okamara** [comment]
<img width="1113" alt="Screen Shot 2020-04-08 at 1 52 35 PM" src="https://user-images.githubusercontent.com/32964663/78776268-3cccbb80-79a0-11ea-9c0b-081a4aac51eb.png">
Verified.
