### ISSUE TITLE
jenkins-master 4.10 still has ZAFIRA_ACCESS_TOKEN

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/jenkins-master#163]
This parameter is no more needed
![image](https://user-images.githubusercontent.com/44428408/78365246-7d56be80-75c7-11ea-861b-9a4ee0706362.png)

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/162

**Comment by ilya-varchenya** [comment]
@okamara and @dhreben, check:
1. there's no ZAFIRA_ACCESS_TOKEN in jenkins configuration
2. tests run and results are displayed in Zafira

**Comment by dhreben** [comment]
Fixed
