### ISSUE TITLE
ghprbhook-token always is assigned to ghbr checker plugin

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#165]
For users who assign their own users/credentials always reset PR checker during jenkins restart

**Comment by vdelendik** [comment]
@okamara, test scenarios:
1) sudo ./clear.sh
2) update jenkins-master to 4.10.1
3) start infra
-> manage jenkins configure system should have assigned CHANGE_ME/.. for github pull request checker
![image](https://user-images.githubusercontent.com/4551455/78480363-2cbd9d80-774e-11ea-83fb-e443d8226111.png)
4) add new test credentials and assign to github pull request checker plugin
5) restart infra
6) examine github pull request checker plugin setup
-> new test user should be assigned. in 4.10 it automatically reset back to CHANGE_ME

**Comment by okamara** [comment]
Tested.
<img width="639" alt="Screen Shot 2020-04-06 at 5 11 14 PM" src="https://user-images.githubusercontent.com/32964663/78568018-30265700-782a-11ea-92e0-e00a1169b8fd.png">
<img width="675" alt="Screen Shot 2020-04-06 at 5 11 36 PM" src="https://user-images.githubusercontent.com/32964663/78568028-33b9de00-782a-11ea-86ab-ef82105991c4.png">

**Comment by okamara** [comment]
Tests of pull request builder is not past.
<img width="807" alt="Screen Shot 2020-04-06 at 5 47 52 PM" src="https://user-images.githubusercontent.com/32964663/78572750-839ba380-7830-11ea-8d64-a8f1d80ac3e0.png">

**Comment by okamara** [comment]
Reverified. Fixed.
