### ISSUE TITLE
ROOT_URL value should be applicable only for first init run

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#169]
as only JENKINS_SECURITY_INITIALIZED=true we shouldn't update this value in Jenkins as it might override manually entered value

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/171/files

**Comment by okamara** [comment]
Verified.
![Uploading Screen Shot 2020-04-10 at 4.33.38 PM.png…]()
