### ISSUE TITLE
Git block shows Error messages

### ISSUE THREAD

**Issue by okamara** [qaprosoft/jenkins-master#172]
Steps:
Update jenkins-master qaprosoft/jenkins-master:4.11-beta1
save end exit
delete jenkins folder content: rm -rf ./jenkins/*
./start.sh
wait for a couple of minutes
open Jenkins -> Manage Jenkins -> Global tool configuration
verify that Git block doesn't show any Error messages
Actual result: Git block shows Error messages

<img width="1116" alt="Screen Shot 2020-04-08 at 1 54 29 PM" src="https://user-images.githubusercontent.com/32964663/78778089-5ae7eb00-79a3-11ea-9d82-caba189f1e78.png">

**Comment by vdelendik** [comment]
fixed indirectly with new jenkins. it can be verified on latest qps-infra from develop branch.
http://demo.qaprosoft.com/jenkins/configureTools/

![image](https://user-images.githubusercontent.com/4551455/81017110-5d3a4980-8e6a-11ea-8536-bdf2f5ccb240.png)

**Comment by dhreben** [comment]
fixed 
<img width="1122" alt="Screen Shot 2020-05-05 at 14 28 17" src="https://user-images.githubusercontent.com/50950954/81061298-c195f100-8edc-11ea-8ebb-541c5a72f53b.png">
