### ISSUE TITLE
invalid field detected zafiraRefreshToken

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#174]
![image](https://user-images.githubusercontent.com/4551455/78995466-113a0480-7b4b-11ea-89bd-d8a9530a4d46.png)

it should be zafiraAccessToken

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/175

**Comment by dhreben** [comment]
fixed
