### ISSUE TITLE
Adjust approved method signature available after Jenkins deployment

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/jenkins-master#178]
Currently for Zebrunner pipelines i use the following method signatures allowing me to inspect upstream:
```
method hudson.model.Cause$UpstreamCause getUpstreamProject
method hudson.model.Run getCause java.lang.Class
method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild
```
Those can be seen in Jenkins UI: Jenkins -> Manage Jenkins -> Jenkins -> Manage Jenkins -> In-process Script Approval). 

It would be great if those signatures would be allowed by default on a brand new Jenkins deployment (otherwise manual approval would be required after first Zebrunner pipeline scan)

**Comment by ilya-varchenya** [comment]
@vdelendik, there's no such section on our demo (In-process Script Approval)
![image](https://user-images.githubusercontent.com/44428408/84003812-41e3c200-a973-11ea-8265-76213b98b6f8.png)
I checked it's absence on my own jenkins

I'm going to find solution for this issue, maybe we need to install some plugins

**Comment by ilya-varchenya** [comment]
It seems that it can be Jenkins bug
This parameter presents on okamara's testing environment
okamara's jenkins version - 2.239
demo's jenkins version - 2.234

**Comment by ilya-varchenya** [comment]
Note: need to check using of jobdsl+pipeline. Run jobdsl+pipeline and this section will appear

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/248

**Comment by okamara** [comment]
I see Jenkins -> Manage Jenkins -> Jenkins -> Manage Jenkins -> In-process Script Approval on  jenkins version - 2.234

**Comment by okamara** [comment]
<img width="1435" alt="Screen Shot 2020-06-12 at 5 39 34 PM" src="https://user-images.githubusercontent.com/32964663/84514556-e21f4b00-acd3-11ea-8983-825766eaf047.png">

**Comment by okamara** [comment]
@ilya-varchenya could you please add details where exactly I need to check this issue.

**Comment by ilya-varchenya** [comment]
@okamara use qaprosoft/jenkins-master:5.1-beta3

**Comment by okamara** [comment]
<img width="1091" alt="Screen Shot 2020-06-15 at 1 11 04 PM" src="https://user-images.githubusercontent.com/32964663/84645750-c0a7a480-af09-11ea-9766-37f15855af97.png">
