### ISSUE TITLE
new changes should appear in management_jobs

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#179]
1. create new jobs using their config.xml files from demo server:
http://demo.qaprosoft.com/jenkins/job/Management_Jobs/job/RegisterQTestCredentials/
http://demo.qaprosoft.com/jenkins/job/Management_Jobs/job/RegisterTestRailCredentials/

2. update RegisterHubCredentials:
folderName is 1st parameter now
"Provider" renamed to "provider"
"Url" renamed to "url"
string params are trimed

3. update RegisterZafiraCredentials:
folderName is 1st parameter
all string params are trimed

4. update DeleteOrganization
folderName is trimed

5. update RegisterOrganization
all string params are trimed

6. update RegisterUserCredentials (@ilya-varchenya why do we need this job?)
all string params are trimed

**Comment by vdelendik** [comment]
test scenario:
1) sudo ./clear.sh
2) start qps-infra using 4.10.2 jenkins-master
3) verify one by one that changes applied
4) launch management jobs in scope of regular acceptance testing to register org/repo
5) also test DeleteOrganization

**Comment by dhreben** [comment]
Verified
