### ISSUE TITLE
be able to specify ghprbhook-token creds from dockerfile variables

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#180]
https://github.com/qaprosoft/jenkins-master/commit/30cef37e3c4024c1f2c5a3ae203be857a565cf71#diff-34494e955486d816c3d3fff54c9e5e37L42

let's declare env vars in Dockerfile so end user could setup them on the initial startup
GHPRBHOOK_USER and GHPRBHOOK_PASS

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/jenkins-master/pull/182

test scenario:
1) sudo ./clear.sh
2) update in docker-compose.yml jenkins-master to 4.10.2
3) declare in variables.env valid credentials for github pull request checker plugin:
GHPRBHOOK_USER=username
GHPRBHOOK_PASS=password
4) start everything and register org and repo
5) pull request checker is fully operational by default without changing credentials in Jenkins

**Comment by okamara** [comment]
Verified. Done.
