### ISSUE TITLE
make JENKINS_OPTS applicable for http only by default

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#181]
default options should use http 8080 port without reference to keystore.jks
ENV JENKINS_OPTS="--prefix=/jenkins --httpPort=-1 --httpsPort=8083 --httpsKeyStore=/var/jenkins_home/keystore.jks --httpsKeyStorePassword=password"

change to
ENV JENKINS_OPTS="--prefix=/jenkins --httpPort=8080"

**Comment by vdelendik** [comment]
PR: https://github.com/qaprosoft/jenkins-master/pull/183

test scenario:
1) start jenkins-master using command ilne from README:
docker run -p 8080:8080 -p 50000:50000 \
          -v ~/jenkins_home:/var/jenkins_home -v ~/.m2:/root/.m2 -v ~/.ssh:/var/jenkins_home/.ssh 
          -e JENKINS_OPTS="--httpPort=8080" \
          -d --rm --name jenkins qaprosoft/jenkins-master:latest
2) jenkins should be up&running and accessible by
http://myhost-ip:8080/jenkins
3) creds to login admin/qaprosoft

**Comment by okamara** [comment]
After run the commans jenkins is not available on 
http://myhost-ip:8080/jenkins

**Comment by okamara** [comment]
<img width="955" alt="Screen Shot 2020-04-13 at 7 56 36 PM" src="https://user-images.githubusercontent.com/32964663/79140801-3768da00-7dc1-11ea-95fd-f15bdbe96a0b.png">

**Comment by vdelendik** [comment]
@okamara, verified successfully but found and fix several mistakes in readme for that.
