### ISSUE TITLE
MAX_SURVIVABILITY is specified after configuring jenkins from scratch

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#191]
![image](https://user-images.githubusercontent.com/4551455/80011112-1183b980-84d4-11ea-986f-7fc8d58cccfa.png)

manege jenkins -> configure system
Pipeline Speed/Durability Settings: MAX_SURVIVABILITY

for qa automation it is not a good option. we should have by default:
Performance-optiomized...

please adjust configuration groovy script. I suppose it is a regression

**Comment by vdelendik** [comment]
not a bug as already correctly defined after startup

**Comment by vdelendik** [comment]
stiil detected on demo

**Comment by sandinosanchez** [comment]
#224

**Comment by okamara** [comment]
![Uploading Screen Shot 2020-05-15 at 7.00.15 PM.png…]()
Tested. Done
