### ISSUE TITLE
provide independent docker-compose.yml 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#192]
in scope of the ticket need to create docker-compose.yml for jenkins-master and several slaves to be as ci layer.
Also in scope of this change we are going to start using shared volumes. 
So need to test carefully starting from scratch and remove in F.A.Q. info about:
General error during conversion: Error grabbing Grapes -- [download failed: org.beanshell#bsh;2.0b4!bsh.jar]

**Comment by vdelendik** [comment]
Changes are available in docker image: jenkins-master:5.0-beta2
in qps-infra branch is: 5.0-beta1

**Comment by okamara** [comment]
Fixed.
