### ISSUE TITLE
test if adding extra plugins with shared volumes is available

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#193]
in 5.0 we don't plan to use shared folders anymore. So need to test how sharing extra_plugins.txt can be organized.
Details for old approach: extra plugins follow this steps: https://github.com/qaprosoft/jenkins-master/releases/tag/4.6

it would be great if we can combine docker volumes and shared location for a single extra_plugins.txt file

**Comment by vdelendik** [comment]
need to test to ensure extra plugin can be installed based on instructions in the previous comment

**Comment by okamara** [comment]
tested by @vdelendik . Done
