### ISSUE TITLE
"Could not create local repository at /var/jenkins_home/.m2/repository" for new Set up env

### ISSUE THREAD

**Issue by okamara** [qaprosoft/jenkins-master#196]
[INFO] [jenkins-event-spy] Generated /var/jenkins_home/jobs/qaprosoft/jobs/carina-demo/jobs/onPullRequest-carina-demo/workspace@tmp/withMaven89fe6634/maven-spy-20200422-200814-2968828558395730732324.log
[ERROR] Could not create local repository at /var/jenkins_home/.m2/repository -> [Help 1]

**Comment by vdelendik** [comment]
Changes are available in docker image: jenkins-master:5.0-beta2
in qps-infra branch is: 5.0-beta1

**Comment by okamara** [comment]
Repository is created with other errors.
