### ISSUE TITLE
setup 3.6.3 maven as default in global tools

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#197]
3.0.6 is current one - need to update configuration part and make 3.6.3 as default

**Comment by vdelendik** [comment]
Changes are available in docker image: jenkins-master:5.0-beta2
in qps-infra branch is: 5.0-beta1

To verify  goto manage jenkins -> configure system -> global tools.
maven installations should have M3 with 3.6.3 version

**Comment by okamara** [comment]
Done. Verified.
![Uploading Screen Shot 2020-04-25 at 11.20.56 AM.png…]()
