### ISSUE TITLE
fix maven settings in docker container

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#198]
1) 3.5.4 maven is installed as of now - let's make it 3.6.3
2) strange ENV var declared:
MAVEN_CONFIG "$USER_HOME_DIR/.m2"
during docker preparation it refers to the inaccessible /root/.m2
let's remove it completely
3) also let's remove such line as well:
VOLUME "$USER_HOME_DIR/.m2"

**Comment by vdelendik** [comment]
Changes are available in docker image: jenkins-master:5.0-beta2
in qps-infra branch is: 5.0-beta1

Please completely remove qps-infra and clone/switch to 5.0-beta1 branch to test

1) 3.6.3 maven installed. to test it please login to jenkins-master container
docker exec -ti id /bin/bash
2) mvn --version
output should be:
_Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: IcedTea, runtime: /usr/lib/jvm/java-1.8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-133-generic", arch: "amd64", family: "unix"_
3) no more errors like "permission denied" during job run and maven dependencies loading

**Comment by okamara** [comment]
I see other errors during scan jobs and repository.

**Comment by vdelendik** [comment]
@okamara do the organization registration with new zafira url and token

**Comment by okamara** [comment]
Fixed.
