### ISSUE TITLE
upgrade jenkins-master to 2.234

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#199]
also take a look to the plugins updates if needed

**Comment by vdelendik** [comment]
2.234 jenkins is available in jenkins-master:5.0-beta9
qps-infra: 5.0-beta8+

list of updated plugins can be found here:
https://github.com/qaprosoft/jenkins-master/commit/ba85bbc4b5cac3c1ad813c6a7a1595ea3f765946

**Comment by okamara** [comment]
Updated jenkins-master:5.0-beta9, qps-infra: 5.0-beta8
