### ISSUE TITLE
Manage Jenkins show errors and warnings after update

### ISSUE THREAD

**Issue by okamara** [qaprosoft/jenkins-master#202]
Tested on docker image: jenkins-master:5.0-beta2
in qps-infra branch is: 5.0-beta1

<img width="1087" alt="Screen Shot 2020-04-25 at 11 25 23 AM" src="https://user-images.githubusercontent.com/32964663/80275103-d8bc2e00-86e7-11ea-9aa0-c4e94466261f.png">
<img width="1090" alt="Screen Shot 2020-04-25 at 11 24 58 AM" src="https://user-images.githubusercontent.com/32964663/80275105-de197880-86e7-11ea-94ac-65b8af5ac78c.png">

**Comment by vdelendik** [comment]
most of the warning and issues fixed:
![image](https://user-images.githubusercontent.com/4551455/80912965-7f887600-8d49-11ea-83b1-c13828005606.png)

#215 is for Resource Root Url

**Comment by okamara** [comment]
Looks like not fixed properly:
<img width="1115" alt="Screen Shot 2020-05-05 at 1 57 38 PM" src="https://user-images.githubusercontent.com/32964663/81059109-7f6ab080-8ed8-11ea-8782-96533051f597.png">
Tested on qaprosoft/jenkins-master:5.0-beta9 and qps-infra: 5.0-beta8
