### ISSUE TITLE
RegisterOrganization job should use new url and token for Zebrunner Insights (zafira)

### ISSUE THREAD

**Issue by okamara** [qaprosoft/jenkins-master#203]
Tested on docker image: jenkins-master:5.0-beta2
in qps-infra branch is: 5.0-beta1

User get errors in Register Repository in console log
<img width="1093" alt="Screen Shot 2020-04-25 at 11 43 12 AM" src="https://user-images.githubusercontent.com/32964663/80275462-04d8ae80-86ea-11ea-8c4b-b2dc210033a4.png">
<img width="1000" alt="Screen Shot 2020-04-25 at 11 43 06 AM" src="https://user-images.githubusercontent.com/32964663/80275467-0b672600-86ea-11ea-9d23-c9d12fc0f3ce.png">

**Comment by vdelendik** [comment]
1. default serviceUrl should be "http://reporting-service:8080/reporting-service" without quotes
2. default token need to be regenerated based on future changes with default admin user

**Comment by okamara** [comment]
Fixed.
