### ISSUE TITLE
rename zafiraServiceUrl and zafiraAccessToken text fields

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#204]
http://demo.qaprosoft.com/jenkins/job/Management_Jobs/job/RegisterZafiraCredentials
http://demo.qaprosoft.com/jenkins/job/Management_Jobs/job/RegisterOrganization/

in both jobs rename text fields:
zafiraServiceUrl -> reportingServiceUrl
zafiraAccessToken -> reportingAccessToken

Also deliver changes together with pipeline modification: 
https://github.com/qaprosoft/qps-pipeline/issues/715

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/208

**Comment by okamara** [comment]
Tested.
<img width="846" alt="Screen Shot 2020-04-29 at 1 47 27 PM" src="https://user-images.githubusercontent.com/32964663/80587867-ff4bd300-8a1f-11ea-97b7-4ca5b1f337c4.png">
