### ISSUE TITLE
rename RegisterZafiraCredentials -> RegisterReportingCredentials

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#205]
http://demo.qaprosoft.com/jenkins/job/Management_Jobs/job/RegisterZafiraCredentials/

let's rename to RegisterReportingCredentials

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/209

**Comment by okamara** [comment]
Tested. Fixed.
