### ISSUE TITLE
add default JAVA_OPTS var for jenkins-master

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#213]
JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/jenkins-master/commit/4a6eab83fc48eeb9a8b2304a1b59aec7d8bcd083

change is available in 
qaprosoft/jenkins-master:5.0-beta8

**Comment by okamara** [comment]
JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true
