### ISSUE TITLE
Need to update SonarGlobalConfiguration in jenkins

### ISSUE THREAD

**Issue by okamara** [qaprosoft/jenkins-master#218]
<img width="1081" alt="Screen Shot 2020-05-05 at 2 58 20 PM" src="https://user-images.githubusercontent.com/32964663/81066877-78e33580-8ee6-11ea-91d7-2d4f2756ed93.png">
<img width="1123" alt="Screen Shot 2020-05-05 at 2 43 55 PM" src="https://user-images.githubusercontent.com/32964663/81066896-7e408000-8ee6-11ea-8ad0-a9207b061613.png">

**Comment by sandinosanchez** [comment]
According to this [post](https://community.sonarsource.com/t/sonar-jenkins-plugin-v2-10-triggering-invalid-data-format-warning-in-jenkins-on-boot/18601) and this jira [ticket](https://jira.sonarsource.com/projects/SONARJNKNS/issues/SONARJNKNS-319?filter=allopenissues) its a bug from the sonar plugin that we are using in jenkins (version 2.11) one workaround is to just discard unreadable data.

Will close this until we hear news from the sonar jira ticket.
