### ISSUE TITLE
remove any reference to pipelineLibrary and runnerClass from registerOrganization

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#222]
pipelineLibrary and runnerClass are specific to the repository mostly. Need to review one more time why it presents on registerOrganization job.

Ideal variant: provide independent registerPipelineLibrary job which can register runner/classes to the organization.
After that RegisterRepository should show editable choice with default ones:
QPS-Pipeline
com.qaprosoft.jenkins.pipeline.runner.maven.QARunner
com.qaprosoft.jenkins.pipeline.runner.maven.Runner
plus already registered custom ones

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/235

**Comment by okamara** [comment]
Fixed.
