### ISSUE TITLE
remove pipelineLibrary and runnerClass from registerOrganization

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#225]
I believe there is no sense in providing pipelineLibrary and runnerClass during RegisterOrganization.
so action plan:
1) remove those args from default job
2) registerRepository job which is created by jobDSL should have above textfields as extensible editable fields.
pipelineLibrary: QPS-Pipeline
runnerClass should have such values by default
com.qaprosoft.jenkins.pipeline.runner.maven.Carina
com.qaprosoft.jenkins.pipeline.runner.maven.TestNG
com.qaprosoft.jenkins.pipeline.runner.maven.JUnit
com.qaprosoft.jenkins.pipeline.runner.maven.Runner

I suppose it has sense to reuse global choice list as we do for gc_BUILD_PRIORITY

@ilya-varchenya, please submit related ticket in qps-pipeline

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/235

**Comment by ilya-varchenya** [comment]
Related ticket https://github.com/qaprosoft/qps-pipeline/issues/753

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/236

**Comment by okamara** [comment]
Fixed.
