### ISSUE TITLE
manual deployment has invalid link to setup_ghprbhook_credentials.groovy

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#233]
on https://github.com/qaprosoft/jenkins-master/tree/develop/manual_deployment page we have:

Setup GitHub Pull Request Builder by setup_ghprbhook_credentials.groovy Warning: Please, verify that Manage Jenkins -> Global Tool Configuration -> Setup GitHub Pull Request Builder credential field contains ghprbhook-token!

Where link to "setup_ghprbhook_credentials.groovy" return 404

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/jenkins-master/commit/1815635e640023925685c6f1145a128fb41e2089

**Comment by okamara** [comment]
Fixed.
