### ISSUE TITLE
Rename zafira_service_url and zafira_access_token

### ISSUE THREAD

**Issue by ilya-varchenya** [qaprosoft/jenkins-master#240]
Rename 
zafira_service_url -> reporting_service_url
zafira_access_token -> reporting_access_token
Also check qps-pipelines

**Comment by ilya-varchenya** [comment]
Created ticket in an appropriate repo

**Comment by dhreben** [comment]
Verified
<img width="1154" alt="Screen Shot 2020-06-11 at 15 13 38" src="https://user-images.githubusercontent.com/50950954/84384112-276d4b00-abf6-11ea-8b29-705dfc30a4bb.png">
