### ISSUE TITLE
updated embedded README.txt link descritptions

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-master#252]
inside jenkins there is README.txt links with description:
Quick Launch steps: https://github.com/qaprosoft/qps-infra/blob/master/README.md
Guide: https://qaprosoft.github.io/qps-infra/config-guide/

Description should be changed to:
Guide: https://qaprosoft.github.io/qps-infra/

above guide contains everything including high level info, installation, configuration guides etc

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-master/pull/253

**Comment by ilya-varchenya** [comment]
@okamara and @dhreben verify that embedded README.txt in jenkins contains new link

**Comment by dhreben** [comment]
fixed
<img width="618" alt="Screen Shot 2020-07-07 at 18 46 24" src="https://user-images.githubusercontent.com/50950954/86807191-50142380-c082-11ea-9fad-debe8a13ddeb.png">
