### ISSUE TITLE
Deprecated params in registerOrganization and registerRepository jobs

### ISSUE THREAD

**Issue by sandinosanchez** [qaprosoft/jenkins-master#259]
For 5.1 release the registerOrganization and registerRepository jobs are going to change and in the current 5.1-rc1 jenkins master tag there are irregularities.

From 5.1-rc1 registerOrganization and registerRepository:

<img width="612" alt="Screen Shot 2020-07-09 at 16 11 21" src="https://user-images.githubusercontent.com/43247306/87080905-d81f3800-c1fe-11ea-853e-01271487effa.png">

<img width="683" alt="Screen Shot 2020-07-09 at 16 14 24" src="https://user-images.githubusercontent.com/43247306/87081219-4ebc3580-c1ff-11ea-8980-47d6753b2019.png">

**Comment by sandinosanchez** [comment]
@okamara fixed delivered in #257 

Environment:

 - infra-branch > develop
 - pipeline-branch > develop
 - sonarqube:2.2-beta1

Objective:

 - Verify that the registerOrganization and registerRepository have correct parameters.

Pre conditions:

 - [jenkins-master](https://github.com/qaprosoft/jenkins-master.git) cloned into your aws instance

Test scenario:

 1- cd jenkins-master
 2. git checkout master
 3. git pull
 3. docker build -t qaprosoft/jenkins-master:5.1-rc2 .
 4. cd qps-infra
 5. nano .env.original 
     a. change TAG_JENKINS_MASTER=5.1-rc2
     b. change TAG_SONAR=2.2-beta1
 6. run setup.sh and start.sh
 7. change pipeline-branch > develop in jenkins global configuration
 8. run registerOrganization with qarosoft
 9. run registerRepository with default values

Expected Results:

 8. Parameters in registerOrganization job should look like the screenshot below
<img width="683" alt="Screen Shot 2020-07-09 at 16 45 33" src="https://user-images.githubusercontent.com/43247306/87083821-9d6bce80-c203-11ea-91ff-c030775d4bcd.png">


 9. Parameters in registerRepository should look like the screenshot below
<img width="683" alt="Screen Shot 2020-07-09 at 16 44 57" src="https://user-images.githubusercontent.com/43247306/87083770-89c06800-c203-11ea-94a2-b8e5269f5a3b.png">

And the onPushJob must be successfully executed.

**Comment by okamara** [comment]
I don't see gradle in the list 
<img width="851" alt="Screen Shot 2020-07-10 at 12 00 56 PM" src="https://user-images.githubusercontent.com/32964663/87137189-31da3d80-c2a5-11ea-944c-e04c270e5249.png">
Test env.
infra-branch > develop
pipeline-branch > develop
sonarqube:2.2-beta1
jenkins-master:5.1-rc2

**Comment by okamara** [comment]
In the case when I remove and clone qpsinfra I got errors during Register organization. It look that need to add library before as 
Loading libraries failed

**Comment by okamara** [comment]
Reverified. Fixed.
