### ISSUE TITLE
Jenkins global configuration fixed

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/jenkins-master#85]
I'd like to override globally:
- vnc_mobile

Also it would be nice to set jenkins url during initialization:
<img width="760" alt="Screen Shot 2019-07-01 at 6 01 32 PM" src="https://user-images.githubusercontent.com/1182755/60446579-592a1380-9c2a-11e9-854a-f1300c6e5d5c.png">

**Comment by vdelendik** [comment]
fixed.
@hursevich , provide overridden ROOT_URL to setup in at runtime, for example:
ROOT_URL=http://demo.qaprosoft.com/jenkins
