### ISSUE TITLE
Minify plugins list for cloud version

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/jenkins-master#88]
We have to revise the plugin list to reduce resources consumption for Jenkins in k8s deployment.

**Comment by vdelendik** [comment]
in 4.6 we refactored plugins management a lot. in plugins.txt we put only pure qps-infra plugins.
Also we allowed at run-time to re-download custom exact list using extra_plugins.txt if any.
Steps to setup k8s cloud jenkins should be.
1. create extra_plugins.txt with content (used latest available):
kubernetes-cd:2.1.2
kubernetes-credentials:0.4.1
kubernetes:1.19.0

2. share extra_plugins.txt into the jenkins-master by "/usr/share/jenkins/ref/extra_plugins.txt" path

that's it, all the rest new jenkins-master do automatically reloading list of plugins, calculating dependent etc
